### ISSUE TITLE
Adapt Ex3D of Part5 to color_segmenter.py

### ISSUE THREAD

**Issue by manuelgitgomes** [lucasrdalcol/PSR_Assignment2_P2_G8#1]
Adapt current code to work on a video stream, creating a mask and saving the parameters to a .json file

**Comment by lucasrdalcol** [comment]
Final version implemented in commit https://github.com/lucasrdalcol/PSR_Assignment2_P2_G8/commit/d33750818ccde6b3fcbdf6653d36fd2ff0b2157f.
Mostly of the code took from previous work in Ex3D of [Parte05](https://github.com/miguelriemoliveira/psr_21-22/tree/main/Parte05). You can see this adaptation to our Assignment in commit https://github.com/lucasrdalcol/PSR_Assignment2_P2_G8/commit/f198c308f34c22afa9c8d58b57a2ea894e77b56e.

This initial enhancement was done using Global Variables and several functions, but to optimize the code and make it more Pythonic, we are now using only one function that get the position of the track bars at the time, and using Global Variables anymore, substituting those to partial functions. 

The functionalities of the code remains the same, but now it's more optimized and Pythonic.
