### ISSUE TITLE
Drawing by augmented reality

### ISSUE THREAD

**Issue by lucasrdalcol** [lucasrdalcol/PSR_Assignment2_P2_G8#2]
The script should continuously receive images from the camera. Each image is processed to find the object with the predefined color. Then, the coordinates of the centroid of that object are used to determine the detected position of the pencil. In this position, a dot (or a line) is painted with the defined color and size. The process is repeated for each image received.

ref: https://github.com/miguelriemoliveira/psr_21-22/tree/main/Parte07 
"Desenho por realidade aumentada - ar_paint.py" part, without advanced functionalities.

**Comment by manuelgitgomes** [comment]
My part is concluded. I created 3 functions:

- createMask - Creates a mask using the dictionary loaded in the json files;
- findCentroid - Finds the largest blob and its centroid;
- greenBlob - Paints the largest blob green on the original image;

Here's an image so you can check it out. <br>
![image](https://user-images.githubusercontent.com/58152228/141792284-84bf49a4-5a0e-4582-b4e9-a72be93d7a93.png)

**Comment by manuelgitgomes** [comment]
Closing this issue!
